# -*- coding: utf-8 -*-
"""update_geojson

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JpqTY5RuR9u3zn_s15W7JDtRFUCh9t0
"""

import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

# URL pública del CSV exportado desde Google Sheets
url = "https://docs.google.com/spreadsheets/d/1VvLtxHObVlC4uSQqXzxdAYJR7gLcQw32bH06zrauEek/export?format=csv&gid=0"
sitada = pd.read_csv(url)

# Limpieza de encabezados
sitada.columns = sitada.columns.str.strip().str.upper()

# Crear geometría a partir de columnas LATITUD y LONGITUD
geometry = [Point(xy) for xy in zip(sitada["LONGITUD"], sitada["LATITUD"])]
gdf = gpd.GeoDataFrame(sitada, geometry=geometry, crs="EPSG:5367")

# Guardar GeoJSON
gdf.to_file("sistemas_sitada_lambert.geojson", driver="GeoJSON")