name: Actualizar GeoJSON desde Google Sheets

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora
  workflow_dispatch:     # También se puede ejecutar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: pip install pandas geopandas shapely pyproj fiona

      - name: Ejecutar script para actualizar GeoJSON
        run: python update_geojson.py
